apiVersion: v1
kind: Service
metadata:
  name: python-flask-api-service
spec:
  type: NodePort
  selector:
    app: python-flask-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
